replicaCount: 3

image:
  repository: registry.aaronbatilo.dev/grpc-todo
  tag: invalid
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: cfcr

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/protocol: h2c
    kubernetes.io/ingress.class: traefik-grpc
  hosts:
    - host: todo.aaronbatilo.dev
      paths:
        - /

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 10m
    memory: 10Mi
